all:
	matlab -nojvm -nodisplay -nosplash -r "decisiontree IvyLeague.txt 1 1 1" | tail -n +11
test:
	matlab -nojvm -nodisplay -nosplash -r test | tail -n +11
matlab:
	matlab -nojvm -nodisplay -nosplash