all:
	matlab -nojvm -nodisplay -nosplash -r "decisiontree('IvyLeague.txt',23,2,'1');exit" | tail -n +11
test:
	matlab -nojvm -nodisplay -nosplash -r test | tail -n +11
matlab:
	matlab -nojvm -nodisplay -nosplash